### ISSUE TITLE
优化代理设置的说明及设置架构

### ISSUE THREAD

**Issue by xlive2233** [gnuf0rce/rss-helper#18]
我的本地代理端口为2082，设置如下无法连接。

```
# MAP(host, proxy), default by host=127.0.0.1
proxy: 
  www.google.com: 'http://127.0.0.1:2082'
  twitter.com: 'http://127.0.0.1:2082'
```

日志：https://paste.ubuntu.com/p/BV6drHbPz5/

目前我只有直接开启电脑梯子全局或者NETCH的TUN/TAP模式使用
